# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-15 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjas',
            name='desc',
            field=models.CharField(default='Live with honor, eat with dignity', max_length=255),
            preserve_default=False,
        ),
    ]
