# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-20 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dash', '0002_auto_20180620_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.CharField(default='smoke', max_length=255),
            preserve_default=False,
        ),
    ]
