# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-20 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dash', '0003_user_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.SmallIntegerField(default=0),
        ),
    ]
