# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='arthor',
            field=models.CharField(default='No one', max_length=255),
            preserve_default=False,
        ),
    ]
