# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-22 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.CharField(max_length=10, verbose_name='Order Number')),
                ('scheduled_date', models.DateField(verbose_name='date scheduled')),
            ],
            options={
                'ordering': ['-ordernum'],
            },
        ),
    ]
