# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-22 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0002_shipment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
