# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall', '0003_auto_20180619_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='password1', max_length=200),
        ),
    ]
