# Generated by Django 2.0.6 on 2018-06-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(default='Password1!', max_length=20),
        ),
    ]
