# Generated by Django 2.0.6 on 2018-06-18 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_auto_20180618_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
    ]
