# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_remove_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='years',
            field=models.IntegerField(),
        ),
    ]
