# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20180627_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
    ]
