# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auto_20180627_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='on_roster',
        ),
    ]
