# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_quote_arthor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='arthor',
            new_name='author',
        ),
    ]
